<a href="https://colab.research.google.com/github/Cairo-Henrique/BQC-Quantum-Tech/blob/main/BQC_Listas_Exercicio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install qiskit qiskit-aer pylatexenc qiskit-ibm-runtime

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.6/162.6 kB 5.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 89.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 66.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 60.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 378.6/378.6 kB 24.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 52.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.4/54.4 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.8/75.8 kB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 9.3 MB/s eta 0:00:00
  Created wheel for pylatexenc: filename=pylatexenc-2.10-py3-none-any.whl size=136817 sha256=6d17496a744c4e88f8f8b4de75bcdfe0b6e388248945b3639e7213a99f91a05f
  Stored in directory: /root/.cache/pip/wheels/06/3e/78/fa1588c1ae991bbfd814af2bcac6cef7a178b

# Lista 1 - Bloco 1

Questão 3

In [ ]:
import numpy as np

In [ ]:
def eh_porta(porta: np.ndarray) -> bool:
    try:
        matriz_inversa = np.linalg.inv(porta.copy())
        matriz_adjunta = np.conjugate(porta.copy()).T
        return np.allclose(matriz_inversa, matriz_adjunta)
    except Exception as e:
        return False
    return False

In [ ]:
# Teste
porta = np.array([[  1,  1],
                  [  1, -1]]) / np.sqrt(2)
print(eh_porta(porta))

True


Questão 5

In [ ]:
import numpy as np

In [ ]:
def decodificar(bell: int, b1: bool, b2: bool) -> np.ndarray:
    X = np.array([[0, 1],
                  [1, 0]])
    Z = np.array([[1,  0],
                  [0, -1]])
    porta = np.eye(2)

    # Atribuir bits int
    b1 = 1 if b1 else 0
    b2 = 1 if b2 else 0

    if bell == 0: # |phi+>
        if b2 == 1:
            porta = X
        if b1 == 1:
            porta = Z @ porta

    elif bell == 1: # |psi+>
        if b1 == 0 and b2 == 0:
            porta = X
        elif b1 == 1 and b2 == 0:
            porta = Z @ X
        elif b1 == 1 and b2 == 1:
            porta = Z

    elif bell == 2: # |phi->
        if b1 == 0 and b2 == 0:
            porta = Z
        elif b1 == 0 and b2 == 1:
            porta = X @ Z
        elif b1 == 1 and b2 == 1:
            porta = X #* -1

    elif bell == 3: # |psi->
        if b1 == 0 and b2 == 0:
            porta = Z @ X
        elif b1 == 0 and b2 == 1:
            porta = Z #* -1
        elif b1 == 1 and b2 == 0:
            porta = X
        elif b1 == 1 and b2 == 1:
            porta = porta #* -1
    return porta

In [ ]:
# Teste
bells = ['|phi+>', '|psi+>', '|phi->', '|psi->']
for bell in range(4):
    print(f"Bell: {bells[bell]}")
    for b1 in [False, True]:
        for b2 in [False, True]:
            print(f"Bits: {1 if b1 else 0}{1 if b2 else 0}")
            print(decodificar(bell, b1, b2))

Bell: |phi+>
Bits: 00
[[1. 0.]
 [0. 1.]]
Bits: 01
[[0 1]
 [1 0]]
Bits: 10
[[ 1.  0.]
 [ 0. -1.]]
Bits: 11
[[ 0  1]
 [-1  0]]
Bell: |psi+>
Bits: 00
[[0 1]
 [1 0]]
Bits: 01
[[1. 0.]
 [0. 1.]]
Bits: 10
[[ 0  1]
 [-1  0]]
Bits: 11
[[ 1  0]
 [ 0 -1]]
Bell: |phi->
Bits: 00
[[ 1  0]
 [ 0 -1]]
Bits: 01
[[ 0 -1]
 [ 1  0]]
Bits: 10
[[1. 0.]
 [0. 1.]]
Bits: 11
[[0 1]
 [1 0]]
Bell: |psi->
Bits: 00
[[ 0  1]
 [-1  0]]
Bits: 01
[[ 1  0]
 [ 0 -1]]
Bits: 10
[[0 1]
 [1 0]]
Bits: 11
[[1. 0.]
 [0. 1.]]


Questão 7

In [ ]:
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit, generate_preset_pass_manager
from qiskit_ibm_runtime import Sampler
from qiskit_aer import AerSimulator

In [ ]:
def qual_porta_duas_iteracoes(porta) -> int: # 0: I, 1: X, 2: Y, 3: Z
    qr = QuantumRegister(2)
    cr = ClassicalRegister(2, name="bits")
    qc = QuantumCircuit(qr, cr)
    porta(qc, 0)
    qc.h(1)
    porta(qc, 1)
    qc.h(1)
    qc.measure([0, 1], [0, 1])
    backend = AerSimulator()
    pm = generate_preset_pass_manager(backend=backend)
    isa_qc = pm.run(qc)
    sampler = Sampler(backend)
    job = sampler.run([isa_qc], shots=100)
    result = job.result()[0]
    counts = result.data["bits"].get_counts()
    if '00' in counts.keys():
        return 0 # I
    elif '01' in counts.keys():
        return 1 # X
    elif '10' in counts.keys():
        return 3 # Z
    return 2 # Y

In [ ]:
def qual_porta(porta) -> int:
    qr = QuantumRegister(2)
    cr = ClassicalRegister(2, name="bits")
    qc = QuantumCircuit(qr, cr)

    # Preparar um par de Bell |phi+>
    qc.h(0)
    qc.cx(0, 1)

    # Aplicar porta misteriosa
    porta(qc, 0)

    # Decodificar par único
    qc.cx(0, 1)
    qc.h(0)

    qc.measure([0,1], [0,1])
    backend = AerSimulator()
    pm = generate_preset_pass_manager(backend=backend)
    isa_qc = pm.run(qc)
    sampler = Sampler(backend)
    job = sampler.run([isa_qc], shots=10)
    result = job.result()[0]
    counts = result.data["bits"].get_counts()

    if '00' in counts:
        return 0 # I
    elif '01' in counts:
        return 3 # Z
    elif '10' in counts:
        return 1 # X
    return 2 # Y

In [ ]:
def porta(qc, qubit):
    qc.id(qubit)

In [ ]:
qual_porta(porta)

0

# Lista 2 - Bloco 2